backend:
  name: github
  repo: sukunafreesoft/z
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "html_pages"
    label: "HTML Pages"
    folder: "pages"
    create: true
    format: "frontmatter"
    extension: "html"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "HTML Content", widget: "code", default_language: "html" }

  - name: "styles"
    label: "CSS Styles"
    folder: "css"
    create: true
    format: "frontmatter"
    extension: "css"
    fields:
      - { name: "body", label: "CSS Content", widget: "code", default_language: "css" }

  - name: "scripts"
    label: "JavaScript Files"
    folder: "js"
    create: true
    format: "frontmatter"
    extension: "js"
    fields:
      - { name: "body", label: "JavaScript Content", widget: "code", default_language: "javascript" }

  - name: "images"
    label: "Images"
    folder: "img"
    create: true
    fields:
      - { name: "image", label: "Image", widget: "image" }

  - name: "sounds"
    label: "Sounds"
    folder: "sounds"
    create: true
    fields:
      - { name: "file", label: "Sound File", widget: "file" }
      - { name: "description", label: "Description", widget: "text" }

  - name: "log_images"
    label: "Log Images"
    folder: "log-img"
    create: true
    fields:
      - { name: "image", label: "Image", widget: "image" }
      - { name: "alt", label: "Alt Text", widget: "string" }
