backend:
  name: github
  repo: sukunafreesoft/z  # Укажи имя твоего репозитория на GitHub
  branch: main  # или другая ветка, если используешь её

media_folder: "/img"  # Папка для загрузки изображений
public_folder: "/img"  # Путь для отображения изображений

collections:
  - name: "/"
    label: "/"
    folder: "/"  # Папка, где будут храниться твои страницы
    create: true
    slug: "{{slug}}"  # Будет использоваться как имя файла
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }
