backend:
  name: github
  repo: sukunafreesoft/z  # Укажи имя твоего репозитория на GitHub
  branch: main  # Ветка, с которой работаешь

media_folder: "img"  # Папка для загрузки изображений (относительно репозитория)
public_folder: "/img"  # Путь для отображения изображений

collections:
  # Коллекция для HTML-страниц
  - name: "html_pages"
    label: "HTML Pages"
    folder: "/"  # Корневая папка, где хранятся HTML-файлы
    create: true  # Возможность создавать новые файлы
    format: "frontmatter"  # Использовать YAML frontmatter
    extension: "html"  # Расширение файлов
    fields:
      - { name: "title", label: "Title", widget: "string" }  # Заголовок страницы
      - { name: "body", label: "HTML Content", widget: "code", default_language: "html" }  # Основной HTML-код

  # Коллекция для CSS-стилей
  - name: "styles"
    label: "CSS Styles"
    folder: "css"  # Папка со стилями
    create: true
    format: "frontmatter"
    extension: "css"
    fields:
      - { name: "body", label: "CSS Content", widget: "code", default_language: "css" }  # Основной код стилей

  # Коллекция для JavaScript
  - name: "scripts"
    label: "JavaScript Files"
    folder: "js"  # Папка со скриптами
    create: true
    format: "frontmatter"
    extension: "js"
    fields:
      - { name: "body", label: "JavaScript Content", widget: "code", default_language: "javascript" }  # Основной код JS

  # Коллекция для изображений
  - name: "images"
    label: "Images"
    folder: "img"  # Папка с изображениями
    create: true
    media_folder: "img"
    public_folder: "/img"
    fields:
      - { name: "image", label: "Image", widget: "image" }  # Выбор изображения
      - { name: "alt", label: "Alt Text", widget: "string" }  # Описание изображения

  # Коллекция для звуков (если они используются)
  - name: "sounds"
    label: "Sounds"
    folder: "sounds"  # Папка со звуками
    create: true
    fields:
      - { name: "file", label: "Sound File", widget: "file" }  # Выбор файла
      - { name: "description", label: "Description", widget: "text" }  # Описание звука

  # Коллекция для дополнительных файлов (например, в папке log-img)
  - name: "log_images"
    label: "Log Images"
    folder: "log-img"  # Папка с логотипами или изображениями
    create: true
    media_folder: "log-img"
    public_folder: "/log-img"
    fields:
      - { name: "image", label: "Image", widget: "image" }
      - { name: "alt", label: "Alt Text", widget: "string" }
