backend:
  name: github
  repo: sukunafreesoft/z # Замените на ваш репозиторий
  branch: main # Ветка, с которой вы работаете

media_folder: "img" # Папка для загрузки файлов (относительно корня репозитория)
public_folder: "/img" # URL путь для загруженных файлов

collections:
  # Коллекция для HTML-страниц
  - name: "pages"
    label: "Pages"
    folder: "/" # Папка для хранения страниц
    create: true
    format: "frontmatter" # Используем фронтматтер
    extension: "html"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Content", widget: "markdown" }

  # Коллекция для изображений
  - name: "images"
    label: "Images"
    folder: "static/img" # Папка для хранения изображений
    create: true
    fields:
      - { name: "image", label: "Image", widget: "image" }

  # Коллекция для файлов
  - name: "files"
    label: "Files"
    folder: "static/files" # Папка для хранения файлов
    create: true
    fields:
      - { name: "file", label: "File", widget: "file" }
