backend:
  name: github
  repo: sukunafreesoft/z  # Укажи имя твоего репозитория на GitHub
  branch: main  # Ветка, с которой работаешь

media_folder: "img"  # Папка для загрузки изображений (относительно репозитория)
public_folder: "/img"  # Путь для отображения изображений

collections:
  # Коллекция для HTML-страниц
  - name: "html_pages"
    label: "HTML Pages"
    folder: "pages"  # Указываем конкретную папку для HTML
    create: true
    format: "frontmatter"  # Используем YAML фронтматтер
    extension: "html"  # Расширение файлов
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "HTML Content", widget: "code", default_language: "html" }

  # Коллекция для CSS-стилей
  - name: "styles"
    label: "CSS Styles"
    folder: "css"
    create: true
    format: "frontmatter"  # Используем YAML фронтматтер
    extension: "css"
    fields:
      - { name: "body", label: "CSS Content", widget: "code", default_language: "css" }

  # Коллекция для JavaScript
  - name: "scripts"
    label: "JavaScript Files"
    folder: "js"
    create: true
    format: "frontmatter"  # Используем YAML фронтматтер
    extension: "js"
    fields:
      - { name: "body", label: "JavaScript Content", widget: "code", default_language: "javascript" }

  # Коллекция для изображений
  - name: "images"
    label: "Images"
    folder: "img"
    create: true
    fields:
      - { name: "image", label: "Image", widget: "image" }

  # Коллекция для звуков
  - name: "sounds"
    label: "Sounds"
    folder: "sounds"
    create: true
    fields:
      - { name: "file", label: "Sound File", widget: "file" }
      - { name: "description", label: "Description", widget: "text" }

  # Коллекция для логотипов или дополнительных изображений
  - name: "log_images"
    label: "Log Images"
    folder: "log-img"
    create: true
    fields:
      - { name: "image", label: "Image", widget: "image" }
      - { name: "alt", label: "Alt Text", widget: "string" }
